---
- name: Install Apache
  hosts: prod
  gather_facts: yes
  become: yes

  tasks:

    - name: install apache
      ansible.builtin.ping:
      when: ansible_facts.os_family == "RedHat"

    - name: install apache ubuntu
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_facts.os_family == "Debian"

    - name: start appache service
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_facts.os_family == "Debian"